function m = electrode_montage()
% electrode_montage    Current experiment montage.

% Author: Ariel Tankus - Autogenerated for clusters.
% Created: 10.08.2005.

%    Cluster: Region: Channel:
m = {
      1,	'LAH6',	6
      2,	'RPSTG1',	40
      3: 4,	'RPSTG2',	41
      5: 6,	'RPSTG3',	42
      7: 8,	'RPMTG1',	48
      9,	'RPMTG3',	50
     10:11,	'RPMTG5',	52
};
