function fid=createLogFileUCLAParadigm(defaultpath,subses,timestamp)

fid=fopen(fullfile(defaultpath, '..', 'Logs', ['logUCLAParadigm_' timestamp '_' subses '.csv']) ,'w');
fprintf(fid,['Time\t'...
    'Event\t'...
    'Block\t'...
    'Trial\t'...
    'Stim\t'...      %=stimCode. same code for '40Hz' and '40Hz-2'
    'StimFileCode\t'...    %=stim. different code for '40Hz' and '40Hz-2'
    'shortenedWAVname\t'...  %'40Hz-2.wav' becomes '40Hz'
    'StimulusName\t'...      %full WAV name e.g. '40Hz-2.wav'
    'Onset\t'...
    'StimulusStop\r\n']);

end